import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/sections/Header";
import { ReactQueryClientProvider } from "@/components/ReactQueryClientProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <ReactQueryClientProvider>
                <body className="flex flex-col mx-auto bg-gray-100 min-h-screen">
                    <Header />
                    {children}
                </body>
            </ReactQueryClientProvider>
        </html>
    );
}
