import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/sections/Header";
import { ReactQueryClientProvider } from "@/components/ReactQueryClientProvider";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
    title: "Gaming Haven Z",
    description: "Generated by create next app",
    icons: {
        icon: "/favicon.webp",
    },
};

const inter = Inter({ 
    subsets: ['latin'],
    weight: ['400', '500', '600', '700'], // Pesos específicos que quieras usar
    variable: '--font-inter',
    display: 'swap'
  })

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${inter.variable}`}>
            <ReactQueryClientProvider>
                <body className="flex flex-col mx-auto bg-gray-100 min-h-screen font-sans">
                    <Header />
                    {children}
                </body>
            </ReactQueryClientProvider>
        </html>
    );
}
